### ISSUE TITLE
undefined method `s3_bucket' for main:Object

### ISSUE THREAD

**Issue by ReenaAcharya** [k1LoW/awspec#356] opened 2018-02-15 18:43 UTC
Hi,

I am getting following error when executing "bundle exec rake spec":-

An error occurred while loading ./spec/name_spec.rb.
Failure/Error:
  describe s3_bucket('my-bucket') do
    it { should exist }
  end

NoMethodError:
  undefined method `s3_bucket' for main:Object
# ./spec/name.rb:5:in `<top (required)>'
No examples found.

Finished in 0.00032 seconds (files took 0.20712 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Any suggestion on this issue, would be very helpful.

Thanks.

**Comment by ReenaAcharya** [comment] 2018-02-16 05:43
Hi,

Any suggestion here would be very helpful.

Thanks.

**Comment by k1LoW** [comment] 2018-02-17 01:31
Could you show me your environment?

- Gemfile
- bundle exec gem list | grep awspec result

**Comment by glasswalk3r** [comment] 2019-03-05 19:33
I strong believe that this issue is related to the environment to use Awspec, not a bug in the project.
I tried to simulate the issue if the S3 bucket doesn't exist (see PR #457) and couldn't get the same exception.
Given this issue is open for more than a year and no feedback was provided by @ReenaAcharya , I would close this issue.

**Comment by glasswalk3r** [comment] 2019-07-23 12:12
@k1LoW , I guess we can safely close this issue, since we already merged a PR that would fix it and no feedback was provided.

**Comment by k1LoW** [comment] 2019-07-24 12:22
@glasswalk3r Thank you !

**Closed by k1LoW** 2019-07-24 12:22 UTC
Labels: help wanted, question
