### ISSUE TITLE
rds_parameter_group parameter check fails with 'method_missing' 

### ISSUE THREAD

**Issue by GenPage** [k1LoW/awspec#527] opened 2021-01-08 18:24 UTC
``` 
    rds_db_parameter_group 'tf-test-kitchen-postgres9' rds.logical_replication
    Failure/Error: its("rds.logical_replication") { should eq '1' }

    NoMethodError:
       undefined method `members' for #<Hash:0x00005594f9828690>
       Did you mean?  member?
     # /home/plangrid/.gems/gems/awspec-1.22.1/lib/awspec/type/base.rb:45:in `method_missing'
     # /home/plangrid/.gems/gems/awspec-1.22.1/lib/awspec/type/rds_db_parameter_group.rb:17:in `method_missing'
     # ./spec/rds_param_group_spec.rb:14:in `block (3 levels) in <top (required)>'
```

**Comment by glasswalk3r** [comment] 2021-08-28 14:49
I confirmed this bug. AWS made a terrible choice of parameter name, since for the respective `Awspec::Type` `rds.logical_replication` is a method invocation chained.

PR #548  fixes this, but only for parameters names that starts with `rds.`.

**Comment by glasswalk3r** [comment] 2021-09-05 01:50
@k1LoW , with the PR merged, I think it's fine to close this issue.

**Comment by k1LoW** [comment] 2021-09-05 05:37
👍

**Closed by k1LoW** 2021-09-05 05:37 UTC
Labels: bug, pull request wanted
